module.exports = {
  Customer: require('./Customer.model'),
  Business: require('./Business.model'),
  Product: require('./Product.model'),
  Calification: require('./Calification.model'),
  Order: require('./Order.model'),
  Service: require('./Service.model'),
  Purchase: require('./Purchase.model'),
  History: require('./History.model'),
  Document: require('./Document.model'),
  Membership: require('./Membership.model'),
  Coupon: require('./Coupon.model'),
  Support: require('./Support.model'),
  Token: require('./Token.model'),
};